x=int(input("정수를 입력하세요 >> "))
import turtle
t=turtle.Pen()
t.shape('turtle')
t.forward(x)
t.right(90)
t.forward(x)
t.right(90)
t.forward(x)
t.right(90)
t.forward(x)
t.backward(x//2)
t.right(180)
t.circle(x//2)
